:imagesdir: ./assets/img
:iconsdir: ./assets/img
:stylesdir: ./assets/css
:scriptsdir: ./assets/js

:numbered:

= AWS Elastic Beanstalk Grails Plugin documentation

== Introduction

== Installation

In BuildConfig.groovy add the following plugin dependency to the "plugins" section (with the latest version of the plugin specified):

    build ':aws-elastic-beanstalk:0.2'

== Configuration

=== Configuring AWS credentials

=== Using a non-default AWS region

By default, the Elastic Beanstalk plugin uses the US-East (Northern Virginia) AWS Region (+us-east-1+). To select a diferent target region, configure a different AWS Elastic Beanstalk service endpoint using one of the available endpoints listed here:

http://docs.aws.amazon.com/general/latest/gr/rande.html#elasticbeanstalk_region

To configure the plugin to use an alternate service endpoint, specify the 

[options="header"]
|===
| Config type | Variable name | Comment |
| +Config.groovy+ | +grails.plugin.awsElasticBeanstalk.serviceEndpointUrl+ | |
| System property | +awsElasticBeanstalk.serviceEndpointUrl+ | |
| Environment variable | +ELASTICBEANSTALK_URL+ | compatible with AWS CLI tool |
|===

For example, to configure the plugin to use the Asia Pacific (Tokyo) Region, add the following to +Config.groovy+:

	grails.plugin.awsElasticBeanstalk.serviceEndpointUrl = 'https://elasticbeanstalk.ap-northeast-1.amazonaws.com'

=== Configuring the target Elastic Beanstalk application and environment

NOTE: The application name must be between 4 and 23 characters long.

.Configuration options for Elastic Beanstalk application name
[options="header"]
|===
| Config type | Variable name | Comment |
| +Config.groovy+ | +grails.plugin.awsElasticBeanstalk.applicationName+ | |
| System property | +awsElasticBeanstalk.applicationName+ | |
| default | +appName+ | the value of Grails +appName+ is used by default if not otherwise specified |
|===

.Configuration options for Elastic Beanstalk environment name
[options="header"]
|===
| Config type | Variable name | Comment |
| +Config.groovy+ | +grails.plugin.awsElasticBeanstalk.environmentName+ | |
| System property | +awsElasticBeanstalk.environmentName+ | |
| default | appName | +"${appname}-default}" is used if not otherwise specified |
|===


==== Defaults

TK document default application/environment name

TK discuss default JVM settings / container settings


== Stopping an environment

The +aws-eb-stop+ command (alias for +aws-eb-terminate-environment+) will terminate the 

Elastic Beanstalk does not currently provide any way to stop a running application without terminating the container.

If you have created other AWS resources tied to the Elastic Beanstalk environment (such as a CloudFront distribution), these may prevent the environment from terminating successfully and will need to be cleaned up separately.


== Elastic Beanstalk configuration

Container-specific options
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html#command-options-general
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html#command-options-java


== Integrating with Jenkins